# Generated by Django 3.1.3 on 2020-11-22 07:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chatapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='image',
            field=models.ImageField(default='Profile/default.png', upload_to='Profile'),
        ),
    ]
